apiVersion: kustomize.config.k8s.io/v1beta1
kind: kustomization
commonLabels:
  app: image-converter-service # ${PROJECT_NAME}

namespace: general # ${PROJECT_NAMESPACE}

resources:
  - horizontalPodAutoscaler.yml
  - namespace.yml
  - service.yml
  - deployment.yml
  - secrets.yml
  - ingress.yml