apiVersion: networking.k8s.io/v1
Kind: NetworkPolicy
metadata:
  name: image-convert-service-np #${PROJECT_NAME}-np
  namespace: general #${PROJECT_NAMESPACE}
spec:
  podSelector:
    matchLabels:
      tier: backend
  policyTypes:
  - Ingress      
  ingress:
  - from:
    - podSelector:
        matchLabels:
          tier: frontend