apiVersion: apps/v1
kind: Secret
metadata:
  name: image-convert-service-screts #${PROJECT_NAME}-secrets
  namespace: general #${PROJECT_NAMESPACE}
type: Opaque
data:
  DATABASE_USER: YXBwdXNlcg==
  DATABASE_PASSWORD: MTIzY2hhbmdlaXQ=
  APPLICATION_USER: 12345
  APPLICATION_PASSWORD: 12345
  
  # echo -n 'appuser' | base64
  # echo -n '123changeit' | base64