apiVersion: v1
kind: ServiceAccount
metadata:
  name: secret-access-sa
  namespace: general
secrets:
- name: default-token-uudge
imagePullSecrets:
- name: myregistrykey

# configure service accounts for pods
# add ImagePullSecrets to a service account
# kubectl create secret docker-registry myregistrykey --docker-server=DUMMY \
#         --docker-username=DUMMY_USERNAME --docker-password=DUMMY_DOCKER_PASSWORD \
#         --docker-email=DUMMY_DOCKER_EMAIL

# using RBAC authorization