
DROP TABLE IF EXISTS IMAGE_CONVERTION;

DROP TABLE IF EXISTS IMAGE_TYPE;

--------------

create table IMAGE_CONVERTION (imgc_id bigint generated by default as identity, imgc_date date, imgc_type varchar(255), imgc_name varchar(255), imgc_size bigint, imgc_text longtext, imt_id bigint, primary key (imgc_id));

create table IMAGE_TYPE (imt_id bigint generated by default as identity, imt_extension varchar(255), imt_desc varchar(255), imt_name varchar(255), primary key (imt_id));

--------------

alter table IMAGE_TYPE add constraint UK_IMT_EXTENSION unique (imt_extension);

alter table IMAGE_CONVERTION add constraint FK_IMT_IMGC foreign key (imt_id) references image_type;