create table IMAGE_CONVERTION (IMGC_ID bigint generated by default as identity, IMGC_NAME varchar(255), IMT_ID bigint, IMGC_SIZE bigint, IMGC_TYPE varchar(255), IMGC_TEXT longtext, IMGC_AREA boolean, IMGC_CREATED date, primary key (IMGC_ID));

create table IMAGE_TYPE (IMT_ID bigint generated by default as identity, IMT_EXTENSION varchar(255), IMT_NAME varchar(255), IMT_DESC varchar(255), IMT_CREATED date, IMT_UPDATED date, primary key (IMT_ID));

alter table IMAGE_TYPE add constraint UK_IMT_EXTENSION unique (IMT_EXTENSION);

alter table IMAGE_CONVERTION add constraint FK_IMT_IMGC foreign key (IMT_ID) references IMAGE_TYPE;