#=====================================================================================================
#
#               IMAGE-CONVERTER-SERVICE-LOCAL
#
#============== Applicaton ===========================================================================
application:
    user_login: user
    user_password: password

#============== Tesseract ============================================================================
tesseract:
    language: ${TESSERACT_LANG:eng}
    folder: ${TESSERACT_FOLDER:/home/fernando/Development/tools/tesseract/tessdata/}
    dpi : ${TESSERACT_DPI:90}

#============== Server ================================================================================
server:
    port: 8080

#============== Actuator ==============================================================================
management:
    server:
        port: 8080
        
#============= Log ====================================================================================
#logging.level.org.hibernate:
#   SQL: debug
#   type.descriptor.sql: debug


#============== Data Source ===========================================================================
spring: 
    sql.init:
        schema-locations: classpath:db/db-schema-local.sql
        data-locations: classpath:db/db-data-local.sql
    datasource:
        driver-class-name: org.h2.Driver
        url: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE;DB_CLOSE_DELAY=-1
        username: sa
        password: password
    h2:
        console:
            enabled: true   
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                generated_statistics: false
                show_sql: false
                jdbc:
                    time_zone: GMT-3               