#=====================================================================================================
#
#               IMAGE-CONVERTER-SERVICE
#
#=====================================================================================================
info:
    app:
      name: Spring Actuator Application
      description: This is a very simple Spring Boot Application
      version: 1.0.0 # from pom?

#============== Applicaton ===========================================================================
application:
    user_login: ${APPLICATION_USER_LOGIN}
    user_password: ${APPLICATION_USER_PASSWORD}

#============== Open API =============================================================================
springdoc:
  api-docs.enabled: true
  swagger-ui.disable-swagger-default-url: true
#  swagger-ui.use-root-path: true
#  swagger-ui.configUrl: "/v3/api-docs/"
#  swagger-ui.path: "/swagger-ui.html"

#============== Tesseract ============================================================================
tesseract:
    language: ${TESSERACT_LANG}
    folder : ${TESSERACT_FOLDER}
    dpi : ${TESSERACT_DPI:100}

#============== Actuator ==============================================================================
management:
    endpoint:
        health:
            show-details: always
        metrics.enabled: true
    endpoints:
        web:
            discovery:
              enabled: true
            base-path: /actuator
            path-mapping:
                health: /health
            exposure:
                include: "*"
                # exclude: env,beans,mapping,configprops
    server:
       add-application-context-header: true
       port: 5090
       # address: 127.0.0.1 access to the endpoints is restricted only to 127.0.0.1      
#    metrics:
#       export:
#             graphite:
#                step: 3s
# 
#============== Server ==============================================================================
server:
    error.include-message: always 
    http2:
        enabled: true
#    compression:
#        enabled: true        
    port: 8080
    servlet:
        context-path: /
        encoding:
            charset: UTF-8
            enabled: true
            force: true
            force-response: true
    jmx:
        enabled: true
        unique-names: true
#    ssl:
#        enabled: true
#        key-store: classpath:keystore.jks
#        key-store-type: PKCS12
#        key-store-password: password
#        key-password: password
#        key-alias: sb2-recipes

#============== Spring ==============================================================================
spring:
    application:
        name: image-converter-service
    mvc:
        throw-exception-if-no-handler-found: true
#        static-path-pattern: /swagger*
#    cloud:
#        gcp:
#             logging: 
#                 enabled: true
#             trace:
#                 enabled: true
    sleuth:
        enabled: true
        web.client.enabled: true
    jackson:
        default-property-inclusion: NON_NULL     
        
    security: 
        filter.order: 5 # due to multipart resolver

    devtools.add-properties: false

#============== Data Source ===========================================================================
    datasource:
        driver-class-name: ${DATABASE_DRIVER}
        url: ${DATABASE_URL}
        username: ${DATABASE_USER}
        password: ${DATABASE_PASSWORD}
        hikari:
            poolName: SpringBootJPAHikariCP
            connectionTimeout: 60000
            idleTimeout: 30000
            maxLifetime: 2000000
            maximumPoolSize: 20
            minimumIdle: 5
   
    jpa:
        database-platform: ${DATABASE_PLATFORM}
        properties:
            hibernate:
                jdbc:
                    time_zone: GMT-3
            cache:
               region:
                     factory_class: org.hibernate.cache.ehcache.EhCacheRegionFactory
               use_query_cache: true
               use_second_level_cache: true
            javax:
                persistence:
                    retrieveMode:
                        mode: ENABLE_SELECTIVE
                    sharedCache:
                        mode: ENABLE_SELECTIVE